apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  template: 
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        resources:
          requests:
            cpu: "1"
          limits:
            cpu: "1"
